[book]
authors = ["nanfang", "yaodao"]
language = "en"
multilingual = false
src = "src"
title = "Ks-Sdk Help document"

[output.html]
default-theme = "rust"

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]
